"vipcost"
{
    // 火诸葛
    "npc_dota_hero_ancient_apparition" "true"
    // 老诸葛
    "npc_dota_hero_bane" "true"
    // 黄忠
    "npc_dota_hero_arc_warden" "true"
    // 孟获
    "npc_dota_hero_beastmaster" "true"
    // 黄月英
    "npc_dota_hero_viper"  "true"
    // 孙权
    "npc_dota_hero_phantom_lancer"  "true"
    // 周瑜
    "npc_dota_hero_vengefulspirit"  "true"
    // 孙策
    "npc_dota_hero_tiny"  "true"
    // 孙尚香
    "npc_dota_hero_windrunner"  "true"
}